# Setup runtime environment
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
EXPOSE 5000

# Restore packages
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS restore
WORKDIR /src
COPY *.sln .
COPY WebApi/*.csproj ./WebApi/
RUN dotnet restore

# Build project
FROM restore AS build
WORKDIR /src
COPY . .
RUN dotnet build -c Release /p:DefineConstants=\"ALLOWFAKEAUTH\"
RUN dotnet test -c Release
RUN dotnet publish -c Release -o publish_out /p:DefineConstants=\"ALLOWFAKEAUTH\"

# Copy runtime files
FROM runtime
WORKDIR /out
COPY --from=build /src/WebApi/publish_out ./
COPY init.sh .
ENTRYPOINT ["/bin/bash", "init.sh"]
